// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jglhcddmhnmssdnekdrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbGhjZGRtaG5tc3NkbmVrZHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjEzMTYsImV4cCI6MjA1NjU5NzMxNn0.7jJSTx-hB5RcvjWzTRSm4cAwuo4HywMmX44Nuq7dLzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);